version: '3'

services:
  db:
    image: postgres:16
    container_name: postgres-weather
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: weather-ml-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=weather
      - DB_USER=postgres
      - DB_PASSWORD=root
      - API_KEY=${API_KEY}
      - WEATHER_CITY=${WEATHER_CITY}
      - WEATHER_UNITS=${WEATHER_UNITS}
    volumes:
      - ./models:/app/models

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter-weather
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=weather
      - DB_USER=postgres
      - DB_PASSWORD=root
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./models:/app/models
      - ./data:/app/data

volumes:
  pgdata:
