# Dockerfile.jupyter
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir jupyter ipykernel

COPY notebooks/ ./notebooks/
COPY src/ ./src/

ENV PYTHONPATH=/app

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.root_dir=/app/notebooks"]
